;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="InitailizeMaxHealth",NewTagName="InitailizeMaxHealthValue")
+GameplayTagRedirects=(OldTagName="InitailizeMaxHealthValue",NewTagName="Health.Max.Initialize")
+GameplayTagRedirects=(OldTagName="InitializeHealthValue",NewTagName="Health.Current.Initialize")
+GameplayTagList=(Tag="Ability.Action.Sprint",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Sprint.Effect",DevComment="")
+GameplayTagList=(Tag="Health.Current.Initialize",DevComment=" for use Health Attribute Initialize")
+GameplayTagList=(Tag="Health.Max.Initialize",DevComment="")
+GameplayTagList=(Tag="SprintMoveSpeedEffect",DevComment="")
+GameplayTagList=(Tag="Stamina.Current.Initialize",DevComment="")
+GameplayTagList=(Tag="Stamina.Max.Initialize",DevComment="")

